services:
  ktor:
    image: ghcr.io/branneman/health-server:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "127.0.0.1:8080:8080"
    networks: [backend]
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/server-health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  postgres:
    image: postgres:17-alpine
    container_name: health_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init-test-db.sql:/docker-entrypoint-initdb.d/01-init-test-db.sql
    networks: [backend]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:2
    restart: unless-stopped
    env_file: .env
    ports: [ "80:80", "443:443", "443:443/udp" ]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    networks: [backend]
    depends_on:
      ktor:
        condition: service_healthy

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      DOCKER_API_VERSION: "1.47"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: [watchtower]
    command: --interval 60 --cleanup --rolling-restart

volumes:
  pgdata: { }
  caddy_data: { }

networks:
  backend:
    driver: bridge
  watchtower:
    driver: bridge
